---
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:<password>@ac-kya15la-shard-00-00.iyzmums.mongodb.net:27017,ac-kya15la-shard-00-01.iyzmums.mongodb.net:27017,ac-kya15la-shard-00-02.iyzmums.mongodb.net:27017/?ssl=true&replicaSet=atlas-ferf2q-shard-0&authSource=admin&retryWrites=true&w=majority}
  jackson:
    default-property-inclusion: non_null

server:
  port: ${PORT:8080}

oliot:
  tsd:
    config:
      GOOGLE_MANAGER_ID: ${GOOGLE_MANAGER_ID:UA-106158007-1}